### ISSUE TITLE
this does not work in Apple Silicon

### ISSUE THREAD

**Issue by Tonguc-Endem** [jeremy-jr-benthum/onion-browser-button#30]
I'm on M1 Monterey

says:
`dyld[32609]: Library not loaded: '/opt/local/lib/libevent-2.0.5.dylib'`

I installed homebrew and installed libevent but it installs it to /opt/homebrew/lib/libevent-2.1.7.dylib

so I did `sudo ln -s /opt/homebrew/lib/libevent-2.1.7.dylib ./libevent-2.0.5.dylib`

now it says:
```
dyld[32609]: Library not loaded: '/opt/local/lib/libevent-2.0.5.dylib'
  Referenced from: '/Applications/tor_node/tor'
  Reason: tried: '/opt/local/lib/libevent-2.0.5.dylib' (mach-o file, but is an incompatible architecture (have (arm64), need (x86_64))), '/usr/local/lib/libevent-2.0.5.dylib' (no such file), '/usr/lib/libevent-2.0.5.dylib' (no such file), '/opt/homebrew/Cellar/libevent/2.1.12/lib/libevent-2.1.7.dylib' (mach-o file, but is an incompatible architecture (have (arm64), need (x86_64))), '/usr/local/lib/libevent-2.1.7.dylib' (no such file), '/usr/lib/libevent-2.1.7.dylib' (no such file)
```

**Comment by hmh38324** [comment]
+1

**Comment by cherished-fucker** [comment]
+1

**Comment by Kinkazma** [comment]
Sonoma 14.2.1

@MacBook-Pro-3 ~ % cd /Users/XXX/TOR 
@MacBook-Pro-3 TOR % chmod +x run.sh
@MacBook-Pro-3 TOR % ./run.sh



------------  Configure TOR  ------------
1. Start TOR connection
2. Log connection info
3. Stop TOR connection
4. Debug TOR connection
5. New TOR identity
6. Restart TOR connection
-----------------------------------------


----------------------------------------------
------------ Start Tor Connection ------------
----------------------------------------------


events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn tor ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by Kinkazma** [comment]
Last login: Mon Jan 29 02:14:19 on ttys000
kinkazma@MacBook-Pro-3 ~ % ls /usr/local/lib/libevent*.dylib
/usr/local/lib/libevent-2.1.6.dylib
/usr/local/lib/libevent.dylib
/usr/local/lib/libevent_core-2.1.6.dylib
/usr/local/lib/libevent_core.dylib
/usr/local/lib/libevent_extra-2.1.6.dylib
/usr/local/lib/libevent_extra.dylib
/usr/local/lib/libevent_openssl-2.1.6.dylib
/usr/local/lib/libevent_openssl.dylib
/usr/local/lib/libevent_pthreads-2.1.6.dylib
/usr/local/lib/libevent_pthreads.dylib
kinkazma@MacBook-Pro-3 ~ % otool -L /usr/local/bin/tor
/usr/local/bin/tor (architecture x86_64):
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	@executable_path/libevent-2.1.7.dylib (compatibility version 8.0.0, current version 8.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1319.100.3)
/usr/local/bin/tor (architecture arm64):
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	@executable_path/libevent-2.1.7.dylib (compatibility version 8.0.0, current version 8.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1319.100.3)
kinkazma@MacBook-Pro-3 ~ % DYLD_LIBRARY_PATH=/usr/local/lib /usr/local/bin/tor
dyld[49150]: Library not loaded: @executable_path/libevent-2.1.7.dylib
  Referenced from: <46FC139A-C36B-3BF8-9CE2-8188A3C132BA> /usr/local/bin/tor
  Reason: tried: '/usr/local/bin/libevent-2.1.7.dylib' (no such file), '/usr/lib/libevent-2.1.7.dylib' (no such file, not in dyld cache)
zsh: abort      DYLD_LIBRARY_PATH=/usr/local/lib /usr/local/bin/tor
kinkazma@MacBook-Pro-3 ~ % chmod +rx /usr/local/lib/libevent-2.1.7.dylib
chmod: /usr/local/lib/libevent-2.1.7.dylib: No such file or directory
kinkazma@MacBook-Pro-3 ~ % ls /usr/local/lib/libevent*.dylib
/usr/local/lib/libevent-2.1.6.dylib		/usr/local/lib/libevent_extra.dylib
/usr/local/lib/libevent.dylib			/usr/local/lib/libevent_openssl-2.1.6.dylib
/usr/local/lib/libevent_core-2.1.6.dylib	/usr/local/lib/libevent_openssl.dylib
/usr/local/lib/libevent_core.dylib		/usr/local/lib/libevent_pthreads-2.1.6.dylib
/usr/local/lib/libevent_extra-2.1.6.dylib	/usr/local/lib/libevent_pthreads.dylib
kinkazma@MacBook-Pro-3 ~ % chmod +rx /usr/local/lib/libevent-2.1.6.dylib
kinkazma@MacBook-Pro-3 ~ % brew install libevent
==> Downloading https://formulae.brew.sh/api/formula.jws.json
##O=-#   #                                                                                                                     
==> Downloading https://formulae.brew.sh/api/cask.jws.json

Warning: libevent 2.1.12_1 is already installed and up-to-date.
To reinstall 2.1.12_1, run:
  brew reinstall libevent
kinkazma@MacBook-Pro-3 ~ % ls /usr/local/lib/libevent*.dylib
/usr/local/lib/libevent-2.1.6.dylib		/usr/local/lib/libevent_extra.dylib
/usr/local/lib/libevent.dylib			/usr/local/lib/libevent_openssl-2.1.6.dylib
/usr/local/lib/libevent_core-2.1.6.dylib	/usr/local/lib/libevent_openssl.dylib
/usr/local/lib/libevent_core.dylib		/usr/local/lib/libevent_pthreads-2.1.6.dylib
/usr/local/lib/libevent_extra-2.1.6.dylib	/usr/local/lib/libevent_pthreads.dylib
kinkazma@MacBook-Pro-3 ~ % ln -s /usr/local/lib/libevent-2.1.7.dylib @executable_path/libevent-2.1.7.dylib
ln: @executable_path/libevent-2.1.7.dylib: No such file or directory
kinkazma@MacBook-Pro-3 ~ % ls @executable_path
ls: @executable_path: No such file or directory
kinkazma@MacBook-Pro-3 ~ % ln -s /usr/local/lib/libevent-2.1.7.dylib /usr/local/lib/libevent-2.1.7.dylib
kinkazma@MacBook-Pro-3 ~ % ls /usr/local/lib/libevent*.dylib                                              
/usr/local/lib/libevent-2.1.6.dylib		/usr/local/lib/libevent_extra.dylib
/usr/local/lib/libevent-2.1.7.dylib		/usr/local/lib/libevent_openssl-2.1.6.dylib
/usr/local/lib/libevent.dylib			/usr/local/lib/libevent_openssl.dylib
/usr/local/lib/libevent_core-2.1.6.dylib	/usr/local/lib/libevent_pthreads-2.1.6.dylib
/usr/local/lib/libevent_core.dylib		/usr/local/lib/libevent_pthreads.dylib
/usr/local/lib/libevent_extra-2.1.6.dylib
kinkazma@MacBook-Pro-3 ~ % chmod +x /usr/local/bin/tor
kinkazma@MacBook-Pro-3 ~ % /Users/kinkazma/TOR 
zsh: permission denied: /Users/kinkazma/TOR
kinkazma@MacBook-Pro-3 ~ % cd /Users/kinkazma/TOR 
kinkazma@MacBook-Pro-3 TOR % ./run.sh



------------  Configure TOR  ------------
1. Start TOR connection
2. Log connection info
3. Stop TOR connection
4. Debug TOR connection
5. New TOR identity
6. Restart TOR connection
-----------------------------------------


----------------------------------------------
------------ Start Tor Connection ------------
----------------------------------------------


dyld[49424]: Library not loaded: @executable_path/libevent-2.1.7.dylib
  Referenced from: <DE434D5F-01A3-328D-84A5-DCE191A8DB0A> /usr/local/bin/tor
  Reason: tried: '/usr/local/bin/libevent-2.1.7.dylib' (no such file), '/usr/lib/libevent-2.1.7.dylib' (no such file, not in dyld cache)

Tor exited with code null

**Comment by Kinkazma** [comment]
Lol ! J'ai trouvé une solution. Bon, vous installez tor browser. Allez dans :
/Applications/Tor.app/Contents/MacOS/Tor/tor
Copiez l'éxécutable. Collez le où vous voulez. Puis dans le doutes faites un petit chmod +x /nom de chemin.
Double cliquez, attendez, et voilà, l'extension est opérationnelle. Allez, Faites un script shell, mettez ça dans un raccourci macos à chaque lancement ou un truc du genre, chaque jour, ou comme vous voulez, et voilà.

**Comment by Kinkazma** [comment]
Lol ! J'ai trouvé une solution. Bon, vous installez tor browser. Allez dans :
/Applications/Tor.app/Contents/MacOS/Tor/tor
Copiez l'éxécutable. Collez le où vous voulez. Puis dans le doutes faites un petit chmod +x /nom de chemin.
Double cliquez, attendez, et voilà, l'extension est opérationnelle.
Au début j'ai essayé de le mettre dans le dossiez qu'on doit télécharger ici, mais en faisant 1 je suis tombé sur le même problème que vous... Donc j'ai tenté tout un tas de trucs comme vous pouvez le voir, mais je me suis lassé et j'ai voulu ouvrir l'éxécutable que j'avais remplacé, et qui ne faisait pas le même poids, ça a eu l'air de fonctionner bien étrangement, et même de fonctionner avec l'extension... ça me déroute mais bon.

**Comment by Kinkazma** [comment]
In Apple Script Editor 👍 
`tell application "Terminal"
	do script "/Applications/Tor.app/Contents/MacOS/firefox" in window 1
	delay 5
	do script "killall -9 firefox"
	delay 3
	close
	quit
end tell
delay 1
tell application "Tor"
	quit
end tell
tell application "Terminal"
	activate
	delay 4
	do script "/Applications/Tor.app/Contents/MacOS/Tor/tor"
	delay 20
	close
	quit
end tell`

**Comment by Kinkazma** [comment]
In Apple Script Editor 👍 
`tell application "Terminal"
	do script "/Applications/Tor.app/Contents/MacOS/firefox" in window 1
	delay 5
	do script "killall -9 firefox"
	delay 3
	close
	quit
end tell
delay 1
tell application "Tor"
	quit
end tell
tell application "Terminal"
	activate
	delay 4
	do script "/Applications/Tor.app/Contents/MacOS/Tor/tor"
	delay 20
	close
	quit
end tell`

tell application "Terminal"
	do script "/Applications/Tor.app/Contents/MacOS/firefox" in window 1
	delay 5
	do script "killall -9 firefox"
	delay 3
	close
	quit
end tell
delay 1
tell application "Tor"
	quit
end tell
tell application "Terminal"
	activate
	delay 4
	do script "/Applications/Tor.app/Contents/MacOS/Tor/tor"
	delay 20
	close
	quit
end tell

**Comment by Kinkazma** [comment]
> In Apple Script Editor 👍 `tell application "Terminal" do script "/Applications/Tor.app/Contents/MacOS/firefox" in window 1 delay 5 do script "killall -9 firefox" delay 3 close quit end tell delay 1 tell application "Tor" quit end tell tell application "Terminal" activate delay 4 do script "/Applications/Tor.app/Contents/MacOS/Tor/tor" delay 20 close quit end tell`
> 
> tell application "Terminal" do script "/Applications/Tor.app/Contents/MacOS/firefox" in window 1 delay 5 do script "killall -9 firefox" delay 3 close quit end tell delay 1 tell application "Tor" quit end tell tell application "Terminal" activate delay 4 do script "/Applications/Tor.app/Contents/MacOS/Tor/tor" delay 20 close quit end tell

J'ai remplacé le nom de Tor Browser par Tor, faites attention pour vous.
